version: 2

registries:
  packagist:
    type: composer-repository
    url: https://repo.packagist.com
    username: token
    password: "${{ secrets.DEPENDABOT_PACKAGIST_TOKEN }}"

updates:
  -   package-ecosystem: composer
      directory: "/"
      schedule:
        interval: daily
        time: "04:00"
      open-pull-requests-limit: 10
      reviewers:
        - "productsupcom/channel-development"
      registries:
        - "packagist"
      allow:
        - dependency-name: "*"
          dependency-type: "production"