version: '3.9'

services:
    php-cli:
        image: 'docker.productsup.com/cde/cde-php-cli-dev:8.2'
        volumes:
            - '${HOME}/.composer/:/root/.composer'
            - './files:/data/productsup'
            - './:/cde/app'
        stdin_open: true
        working_dir: /cde/app
