parameters:
    .container.dumper.inline_factories: true

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $subscriptionKeyHeader: '%env(SUBSCRIPTION_KEY_HEADER)%'
            $apiToken: '%env(API_TOKEN)%'
            $url: '%env(URL)%'

    Productsup\BinCdeShopifyMetafields\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    GuzzleHttp\HandlerStack:
        factory: [ 'GuzzleHttp\HandlerStack', 'create' ]

    GuzzleHttp\ClientInterface:
        factory: [ '@Productsup\BinCdeShopifyMetafields\Export\Infrastructure\Http\ClientFactory', 'make' ]
