parameters:
    .container.dumper.inline_factories: true

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $url: '%env(URL)%'
            $bufferSize: 25
            $username: '%env(USERNAME)%'
            $password: '%env(PASSWORD)%'

    Productsup\BinCdeShopifyMetafields\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    GuzzleHttp\HandlerStack:
        factory: [ 'GuzzleHttp\HandlerStack', 'create' ]

    GuzzleHttp\ClientInterface:
        factory: [ '@Productsup\BinCdeShopifyMetafields\Export\Infrastructure\Http\ClientFactory', 'make' ]

    Productsup\DK\Connector\Application\Progress\CountableProgressHandler: ~

    Productsup\DK\Connector\Application\Output\Feedback\FeedbackDetails: '@Productsup\BinCdeShopifyMetafields\Export\Application\Feedback\Feedback'

when@dev:
    services:
        Productsup\DK\Connector\Application\Feed\OutputFeedForImport: '@Productsup\DK\Connector\Infrastructure\Feed\File\FileOutputFeedForImport'
        Productsup\DK\Connector\Application\Feed\OutputFeedForExport: '@Productsup\DK\Connector\Infrastructure\Feed\File\FileOutputFeedForExport'
        Productsup\DK\Connector\Application\Feed\InputFeedForExportDelta: '@Productsup\DK\Connector\Infrastructure\Feed\File\FileInputFeedForExportDelta'
        Productsup\DK\Connector\Application\Feed\InputFeedForExport: '@Productsup\DK\Connector\Infrastructure\Feed\File\FileInputFeedForExport'
        Productsup\DK\Connector\Application\Logger\ConnectorLogger: '@Productsup\DK\Connector\Infrastructure\Logger\StandardLogger'